### ISSUE TITLE
modem manager unable to acces device of modem

### ISSUE THREAD

**Issue by latiefkhan** [wulfy23/rpi4#12]
exactly the modem manager protocol hasn't work correctly

**Comment by wulfy23** [comment]
hi... thanks for the message...

as I don't use modem manager... I cannot really help much to look into this issue...

all I can suggest is trying the official images (not my build)... on official builds you can get help from the whole forum or on github from the code contributors...

or letting me know if any of my older builds and what versions actually work as expected... ( at the downloads I suggest you try devel/rc4 as this is likely the last best stable version

http://rpi4.wulfy23.info/builds/devel/rpi-4_21.02.0-rc4_1.0.5-2_r16256_extra/

there have been many code updates to modemmanager / qmi recently also...
