### ISSUE TITLE
Will we get a 22.03 build?

### ISSUE THREAD

**Issue by Synapse07** [wulfy23/rpi4#23]
title.
have a good day.

**Comment by rspierz** [comment]
Upgraded yesturday and it seems to be working well. Much appriciated @wulfy23 !

To keep the ball rolling.. I would be happy to invest my time to make this repo self updating to the latest stable openwrt releases. If you are game we could make it as low effort from your side as possible?

**Comment by molly78** [comment]
Upgraded two and zero issues so far

Thanks wulfy23!
