### ISSUE TITLE
is there any way to have this as a docker, or pihole as a docker with it?

### ISSUE THREAD

**Issue by molly78** [wulfy23/rpi4#3]
First off, thanks for the awesome builds!

It just seems like a rpi4 can do 1000x more than what openwrt requires.

Just wondering if the magic that is pihole can be combined on the same pi is all

**Comment by wulfy23** [comment]
thanks for the comment...

were I in need of similar requirement... i'd invert the status quo... and dockerize / lxc / other the openwrt instance on raspiOS/Other... a few options are available now for arm virtualization... but openwrt does not make the best/most user
friendly HostOS...

one user requested rootfs.tar.gz which I did/do provide for this requirement... I believe they use docker on raspbian from memory...

fwiw these things are so modular... I can see a student / cost~power~space concious person making use of this topology... but I'm  bit old school and network centric so lean towards plonking in additional hw-units for each task... just makes fault tolerance / troubleshooting that much easier for core~production devices...

**Comment by molly78** [comment]
Thanks for getting back to me

Yes, a single pi4 handling dockers such as openwrt, pihole, home assistant, dokuwiki, Kodi database, would be awesomely handy for me!

Time to do some more research as each of these really doesn’t require much.

**Comment by wulfy23** [comment]
no worries...

i'll try to remember to upload the rootfs.tar.gz more often...

i'm just polishing off beta PARTUUID support which might help in some of those applications as well...

**Comment by TalalMash** [comment]
Hello! Feel free to copy/modify my LXC Pi-hole LuCI configurator.
