### ISSUE TITLE
release bump / 22.03.3 stuff

### ISSUE THREAD

**Issue by rspierz** [wulfy23/rpi4#30]
Hi Wulfy23, just seeing if a point release is in the works since the latest z stream release (https://openwrt.org/releases/22.03/notes-22.03.3). If we can automate these releases when a z stream is released, let me know - happy to help accomplish it

**Comment by wulfy23** [comment]
thankyou very much for the heads up... and apologies for the few days latency on my end for this one. I don't anticipate any major 'building' drama for point release and am planning on spending at least several hours or two this weekend on the build/s and seeing what eventuates...

last time I spent time on the build I kind of semi-forked codebase to undertake some core stripping and changes for master branch so I have to undo those (in the past I always had single 'tree' with many conditionals)

the other thing I spent a few hours on was messing with the (graphical) updatecheck / notifications and whatnot including alternatives that can provide similar, likely outside of the primary UI...

worst case scenario we should have some images by Saturday night, if need be with command line auto-update only for those who rely on it...

regarding the automation and such, and I totally understand where you are coming from.... and I'm not and never have been against it, it's just a practicality / certainty thing in that without 'offline hand testing' of several things like cross upgrades / downgrades (which I do and have done most builds), (there is also the whole thing of shared repoclones that are used) it's likely to cause more issues than it solves. on average one in every 3-5 builds requires some sort of minor tweak to some part of some logic somewhere also... so the building / testing process is where most of the 'work' happens/has happened for the build. (i guess the whole 'flavour' concept would need rework like beta and such - or there is also the github action lingering possibility which takes us down a road of a) lots of hours andor b) likely much less invasive logic probably a rewrite), current gameplan is to hardfork an nft only master tree and remove carploads of stuff except disk and package re-install features... from there it would possibly be the best place to then undertake any communal automation stuff... 


so thanks again for the offer and you never know...

**Comment by wulfy23** [comment]
hmmm... as in the terse notes, i'll test more tomorrow but;

vpn-policy is gone-ski > "pbr-iptables(!pbr<nft<fw4!)" for now... if you use it and need the GUI / dont want to migrate I can do a separate build with the legacy package

removed argon for initial build just in case it's not working / until I have time to test / update or whatever...

**Comment by LionHeartP** [comment]
Update to release build today and everything went smooth. It took a normal amount of time as well. Everything works here from SQM to Adblock and no weird log entries as of now.
Ty wolfie

**Comment by wulfy23** [comment]
closing, re-open or start new if needed
