### ISSUE TITLE
How To expand disk size?

### ISSUE THREAD

**Issue by brittson** [wulfy23/rpi4#32]
Hi , So I have been trying to expand the image after writing to sd card using Gparted on a different linux machine, I used the same resize method on official Openwrt images successfully , however with this image , it always stuck while booting. I really like this image , saves me a lot of time compiling the necessary packages as its almost complete. So I want to use it to its fullest with a big SD card.

**Comment by wulfy23** [comment]
Happens on first upgrade... so;
-write the factory to router
-upgrade ( preferably my scp the image to /tmp then sysupgrade -R /tmp/<img>

**Comment by brittson** [comment]
thanks
