### ISSUE TITLE
release bump / 23.05.0

### ISSUE THREAD

**Issue by Synapse07** [wulfy23/rpi4#44]
HI, i hope you are having a good time.
would it be possible to update your build to 23.05.0?

**Comment by fastmover45** [comment]
Hi Wulfy

I also hope you are doing well. and am praying you will come back. The Rpi is the best platform for openwrt and this build is the best by a mile.

**Comment by Synapse07** [comment]
maybe its time we stop hoping.

**Comment by fastmover45** [comment]
I was always told to fight for the good and Never give up. There for I still hold out hope.
