### ISSUE TITLE
Realtime Graphs - Realtime Rate page shows no data

### ISSUE THREAD

**Issue by markjsones** [wulfy23/rpi4#50]
@wulfy23
I'm running OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-24.006.68745-9128656
It's my first OpenWrt box, on a Pi4.

All the important stuff works great, and I have learnt a lot.  nlbwmon is cool, and working.
Most of the graphs under Status->Realtime Graphs work fine, but "Rate" tab does not.

It just says 'Collecting data...'
Visiting http://192.168.1.2/cgi-bin/luci/admin/status/realtime/rate_status, I get
{ "nftables": { } }

This suggests the UI is working fine, but underneath something isn't able to collect any data.

I've searched around in the bowels of the thing for hours, but can't find anything to reconfigure or test to help me get any traction.
I've searched the internet, and again failed to find anything that applies in this circumstance.

Any ideas?  Thanks

**Comment by markjsones** [comment]
Should say, Load, Traffic and Connections tabs all work in stats.
I'm not using any wireless devices, so that tab is uninteresting.

**Comment by molly78** [comment]
Rate requires openwrt to be your dhcp server

you can manually add the ip addresses as Wulfy23’s posted about it once. Now where is that

**Comment by markjsones** [comment]
Thanks, that's interesting.  I'm doing DHCP and DNS elsewhere.  On the Openwrt, I've already added MAC addresses, names and IPs into /etc/config/dhcp, so that the names and IPs show up in the nlbwmon dashboards.  But it's not helped on the realtime - rate page.

In /etc/config/dhcp, they are in this format:-

config host
	option name 'anamexxxx'
	option mac 'xx:xx:xx:xx:xx:xx'
	option ip '192.168.1.xxx'

Been looking for the post you mention but can't see it.

**Comment by markjsones** [comment]
Did you find that post @molly78 ?
I had a search and couldn't see it.

**Comment by molly78** [comment]
> Did you find that post @molly78 ? I had a search and couldn't see it.

Man alive, no. It could be buried in the main GitHub super long post maybe?

**Comment by markjsones** [comment]
I'm totally stuck. I can't find the post that @molly78  speaks of, and there's nothing on the internet that helps.

Is @wulfy23  ever about on here?

**Comment by molly78** [comment]
> I'm totally stuck. I can't find the post that @molly78 speaks of, and there's nothing on the internet that helps.
> 
> Is @wulfy23 ever about on here?

Yeah sorry there. It was a side quest in a post I came across but can’t seem to find it again. Gah

where are you @wulfy23. You’re our only hope!

**Comment by wulfy23** [comment]
I think this is probably the link / info molly78 so kindly mentioned.

https://forum.openwrt.org/t/rpi4-community-build/69998/1560

(depends on nft-qos being enabled / started)

**Comment by markjsones** [comment]
Hi, I've used this method to add all my IP addresses into the config.  THANKS.
So I can now see them listed in the UI 'rate' window.
However, there are no counts/rate information being updated.
I will dig into the services to make sure it's all running.

**Comment by wulfy23** [comment]
whether you are running br-lan as bridge (default)... or the 'lan' is a direct interface (eth0 or eth1 etc. aka NOT bridge) might have an impact...

in my case i'm using br-lan... I think there is a bug / service may need a tweak if you just have 'lan' (which I should have done so if you need let me know)


(some commands for anyones future reference for basic enablement and start.. I think I set monitor enable 1 by default tho' just dont enable the service by default)
```
uci set nft-qos.default.monitor_enable='1'
uci commit nft-qos
/etc/init.d/nft-qos enable
/etc/init.d/nft-qos stop
/etc/init.d/nft-qos start
```

EDIT: the mods I made to this seem a little whacky... don't spend too long on this... I will see what I can do... something on my system basically is not 'predictable' so i'll try to nail down / improve on it's logic a little.

**Comment by markjsones** [comment]
I'm running default so br-lan for 'LAN' zone (comprised of eth0).  WAN side is eth1, well eth.911 more accurately.
I have the 'enable' config etc, but cannot see any unix processes running.  What processes should I expect to be running at this point to underpin this?  ps |grep nft and ps |grep qos show nothing relevant

**Comment by wulfy23** [comment]
basically the "service" has two components...

-on startup it sets up some nft "containers" (tables) for each function
-hotplug insertion of hosts into those containers in the case of the "monitor" function (during dhcp assignment / update)

(aka, there is no background process that runs)

in your case, the second function is manual, so in the output of ```nft list ruleset``` you'd just see counters being updated in the 'nft-qos-monitor' tables (upload and or download) i.e.

```
table inet nft-qos-monitor {
	chain upload {
		type filter hook prerouting priority filter; policy accept;
		ip daddr 10.2.3.44 counter packets 0 bytes 0
		ip daddr 10.2.3.45 counter packets 0 bytes 0
		ip daddr 10.2.3.122 counter packets 674209 bytes 986466221
		ip6 saddr fda9:424a:1c04:0:867:f46d:50cc:1f58 counter packets 181 bytes 18364
		ip6 saddr fe80::d663:c6ff:fe8f:15e7 counter packets 22 bytes 1528


```

**Comment by markjsones** [comment]
OK, odd one this, but I think it's sorted.  I think the problem was related to the 'type filter hook....' row, which looked different in the configuration on my openwrt instance.

I've deleted the table with 'nft delete table inet nft-qos-montior', then restarted the services (which recreates the table).
I then populated it again with all my IPs, and it seems to be working!

Thanks Wulfy23!

**Comment by markjsones** [comment]
...and yuk, I won't be using that feature.  Drops my throughput from near 1GBit/sec to 300Mbit/sec
After a reboot or flush of the table the performance returns, but once I add my IP addresses to the nft table, performance dives.  Is this to be expected?

**Comment by wulfy23** [comment]
interesting, thanks for the info will look at that if I ever get faster speeds or have a system setup for such a test internally. otoh, it should not cause such a hit...

**Comment by markjsones** [comment]
OK cool.  FYI, my setup is quite device heavy, so I've added the best part of 500 IP addresses across 192.168.0.1/23 (ie 192.168.0.x and 192.168.1.x), which is probably not typical.  I suspect performance would be dramatically better with even only half the number of IP addresses in the tables.

**Comment by markjsones** [comment]
At some point I might try again with tighter IP address ranges, more accurately reflecting my various DHCP pools - but I stopped looking at this feature when I saw the performance impact.  Generally speaking, I'm sensitive to ANY degradation in performance.  The PI4 is just about up to 1GB/sec, and I'll avoid any determent to performance, even small :-)
