### ISSUE TITLE
When using Putty what is the user and password

### ISSUE THREAD

**Issue by snippem** [wulfy23/rpi4#7]
When i use putty to open the command prompt a user and password is asked.
But when i login as root and then the password i get a acces denied.
Is there anything i am doing wrong?

**Comment by snippem** [comment]
Ohh fairly new with openwrt ;-)

**Comment by snippem** [comment]
Nevermind can be closed

**Comment by wulfy23** [comment]
no problem...

best to ask questions on the forum thread as it may help others and I'm no good maintaining multiple communication channels...
