### ISSUE TITLE
Luci-argon-theme config page missing

### ISSUE THREAD

**Issue by molly78** [wulfy23/rpi4#9]
Just curious if the luci-argon-theme page has been disabled, or is it that I can’t find it?

can’t find anywhere to change any settings of the theme

**Comment by wulfy23** [comment]
g'day... i'm running the version of argon theme prior to the theme settings being implemented...

i did try updating to that version a few times... but the changes required vs benefit was minimal...

you can rm /etc/dark or similar to change it to white tho'

see: https://forum.openwrt.org/t/rpi4-community-build-discontinued/69998/113?u=wulfy23

**Comment by molly78** [comment]
I’ll stick with your builds as they’ve been awesome!

thanks for the fast reply
